// AUTO-GENERATED by scripts/generate-tokens.cjs — DO NOT EDIT DIRECTLY.
// Typen zu tokens.generated.js (aus den Daten abgeleitet). Neu erzeugen: npm run tokens

/** Theme-Schluessel in semanticDefaults */
export type ThemeKey =
  | "neo-light"
  | "neo-dark"
  | "customer-light"
  | "customer-dark"

/** IDs der semantischen Tokens (semanticTokenGroups[].tokens[].id) */
export type SemanticTokenId =
  | "text-primary"
  | "text-secondary"
  | "text-tertiary"
  | "text-inverse"
  | "text-disabled"
  | "text-on-interactive"
  | "text-link"
  | "text-link-hover"
  | "text-success"
  | "text-danger"
  | "text-warning"
  | "text-info"
  | "text-accent"
  | "background-base"
  | "background-secondary"
  | "background-tertiary"
  | "background-quaternary"
  | "background-inverse"
  | "background-disabled"
  | "background-hover"
  | "background-active"
  | "background-accent"
  | "background-accent-secondary"
  | "background-success"
  | "background-danger"
  | "background-warning"
  | "background-info"
  | "paper"
  | "paper-graphit"
  | "paper-beige"
  | "paper-ivory"
  | "paper-warm-taupe"
  | "paper-pearl-white"
  | "paper-mint"
  | "border-primary"
  | "border-secondary"
  | "border-strong"
  | "border-inverse"
  | "border-disabled"
  | "border-success"
  | "border-danger"
  | "border-warning"
  | "border-info"
  | "interactive-default"
  | "interactive-hover"
  | "interactive-active"
  | "interactive-visited"
  | "interactive-focus"
  | "feedback-info"
  | "feedback-success"
  | "feedback-warning"
  | "feedback-danger"
  | "layer-01"
  | "layer-02"
  | "layer-03"
  | "on-surface"
  | "on-layer-01"
  | "on-layer-02"
  | "on-accent"
  | "on-success"
  | "on-warning"
  | "on-danger"
  | "on-info"
  | "surface-stage"
  | "surface-card"
  | "surface-base"
  | "surface-01"
  | "surface-02"
  | "surface-03"
  | "surface-sunken"
  | "accent-surface"
  | "accent-surface-hover"
  | "accent-surface-active"
  | "accent-on"
  | "accent-line"
  | "accent-underline"
  | "accent-text"
  | "border-subtle"
  | "border-control"
  | "border-emphasis"
  | "elevation-0"
  | "elevation-1"
  | "elevation-2"
  | "elevation-3"
  | "focus-inner"
  | "focus-outer"

/** IDs der Komponenten-Gruppen (componentTokenGroups[].id) */
export type ComponentGroupId =
  | "accordion"
  | "alert"
  | "app-store"
  | "aspect-ratio"
  | "avatar"
  | "badge"
  | "badge-row"
  | "banner"
  | "bento-grid"
  | "breadcrumb"
  | "button"
  | "card"
  | "card-grid"
  | "card-grid-cta"
  | "chapternav"
  | "checkbox"
  | "chip"
  | "code-snippet"
  | "compare-table"
  | "container"
  | "content"
  | "cta"
  | "data-table"
  | "device"
  | "dialog"
  | "divider"
  | "drawer"
  | "dropdown-menu"
  | "empty-state"
  | "event"
  | "events"
  | "expanding-panels"
  | "fade-gallery"
  | "feature-list"
  | "fieldset"
  | "file-upload"
  | "footer"
  | "form"
  | "form-block"
  | "form-error"
  | "form-field"
  | "form-hint"
  | "form-label"
  | "gallery"
  | "grid"
  | "hero"
  | "hero-tmob"
  | "hero-tom"
  | "icon"
  | "input"
  | "input-group"
  | "item"
  | "kbd"
  | "label"
  | "logo-wall"
  | "marquee"
  | "media-frame"
  | "metric"
  | "mobile-drawer"
  | "multiselect"
  | "news"
  | "notification"
  | "otp-input"
  | "pagination"
  | "popover"
  | "product-showcase"
  | "progress"
  | "radio"
  | "range"
  | "rating"
  | "search"
  | "searchbar"
  | "section"
  | "section-header"
  | "segmented-control"
  | "select"
  | "shell"
  | "shot"
  | "sidebar"
  | "skeleton"
  | "solution-tabs"
  | "spinner"
  | "status"
  | "stepper"
  | "story-gallery"
  | "switch"
  | "tab-nav"
  | "table"
  | "table-block"
  | "table-info-modal"
  | "tabs"
  | "tag"
  | "tbl-cell"
  | "testimonial"
  | "testimonial-grid"
  | "text-cta"
  | "text-media"
  | "textarea"
  | "timeline"
  | "toast"
  | "toggle-group"
  | "toolbar"
  | "tooltip"
  | "treeview"
  | "validation-summary"
  | "dropdown"
  | "group"
  | "kicker"
  | "mono"
  | "nav"
  | "parallax"
  | "reference-page"
  | "type"
  | "chapter-nav"

export declare const primitiveColors: {
  primary: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
    alias: string
  }
  secondary: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
    alias: string
  }
  accent: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
    alias: string
  }
}

export declare const supportingPalettes: {
  "neo-darkblue": {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  "neo-blue": {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  chartreuse: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  pink: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  aqua: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  cyan: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  burgundy: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  coral: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  mustard: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  "old-gold": {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  "dark-orange": {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
}

export declare const foundationPalettes: {
  black: {
    label: string
    base: string
    shades: {
      "10": string
      "20": string
      "30": string
      "40": string
      "50": string
      "60": string
      "70": string
      "80": string
      "90": string
      "100": string
    }
  }
  white: {
    label: string
    base: string
    shades: {
      "10": string
      "20": string
      "30": string
      "40": string
      "50": string
      "60": string
      "70": string
      "80": string
      "90": string
      "100": string
    }
  }
}

export declare const neutralPalette: {
  neutral: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
}

export declare const paperLadders: {
  graphit: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  blau: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  beige: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  salbei: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  ivory: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  "warm-taupe": {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  "pearl-white": {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  mint: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  forest: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  lime: {
    label: string
    base: string
    shades: {
      "50": string
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
}

export declare const papers: {
  _notiz: string
  liste: string[]
  gruende: string[]
  stufe: number
  attribut: string
  bereiche: {
    graphit: {
      bereich: string
      charakter: string
      website: string
      praesentation: string
      print: string
      voreinstellung: boolean
    }
    beige: {
      bereich: string
      charakter: string
      website: string
      praesentation: string
      print: string
    }
    ivory: {
      bereich: string
      charakter: string
      website: string
      praesentation: string
      print: string
    }
    "warm-taupe": {
      bereich: string
      charakter: string
      website: string
      praesentation: string
      print: string
    }
    "pearl-white": {
      bereich: string
      charakter: string
      website: string
      praesentation: string
      print: string
    }
    mint: {
      bereich: string
      charakter: string
      website: string
      praesentation: string
      print: string
      vorlaeufig: boolean
    }
  }
  reserve: string[]
}

export declare const praesentation: {
  format: {
    breite_zoll: number
    hoehe_zoll: number
  }
  raster_mm: {
    rand: number
    steg: number
    feld: number
    felder: number
  }
  figma: {
    format: {
      breite: string
      hoehe: string
    }
    raster: {
      rand: string
      feld: string
      steg: string
      felder: number
      inhalt_breite: string
    }
    zonen: {
      kicker_y: string
      titel_y: string
      haarlinie_y: string
      inhalt_von_y: string
      inhalt_bis_y: string
      fuss_y: string
    }
    schrift: {
      kicker: {
        familie: string
        groesse: string
      }
      titel: {
        familie: string
        groesse: string
        gewicht: number
      }
      text: {
        familie: string
        groesse: string
      }
      spalten: {
        familie: string
        groesse: string
      }
    }
    farbe: {
      titel: string
      text: string
      mono: string
    }
  }
  dichtestufen: {
    vortrag: {
      label: string
      dateiname: string
      titelzone_mm: number
      titel_pt: number
      text_pt: number
      kicker_pt: number
      fuss_pt: number
      woerter_max: number
    }
    versand: {
      label: string
      dateiname: string
      titelzone_mm: number
      titel_pt: number
      text_pt: number
      kicker_pt: number
      fuss_pt: number
      woerter_max: null
    }
  }
  status: {
    bedeutung: {
      gruen: string
      gelb: string
      rot: string
    }
    hell: {
      gruen: {
        marke: string
        text: string
      }
      gelb: {
        marke: string
        text: string
      }
      rot: {
        marke: string
        text: string
      }
    }
    tief: {
      gruen: {
        marke: string
        text: string
      }
      gelb: {
        marke: string
        text: string
      }
      rot: {
        marke: string
        text: string
      }
    }
  }
  diagramm: {
    farbfolge: string[]
    hervorhebung: string
    achse: string
    beschriftung: string
  }
  gruenfamilie: {
    forest: {
      quelle: string
    }
    mint: {
      quelle: string
    }
    rollen: {
      papier: string
      grund: string
      grund_tief: string
      signal: string
      text_auf_forest: string[]
      mono_auf_forest: string
      text_auf_mint: string[]
      mono_auf_mint: string
      flaeche_auf_mint: string
      flaeche_auf_forest: string
    }
    proportion: {
      forest: string[]
      mint: string[]
    }
  }
  welten: {
    menschen: {
      ebene: string
      hell: string
      satt: string
      tief: string
    }
    wissen: {
      ebene: string
      hell: string
      satt: string
      tief: string
    }
    systeme: {
      ebene: string
      hell: string
      satt: string
      tief: string
    }
    daten: {
      ebene: string
      hell: string
      satt: string
      tief: string
    }
  }
  papiere: {
    liste: string[]
    gruende: string[]
    stufe: number
    attribut: string
    bereiche: {
      graphit: {
        bereich: string
        charakter: string
        website: string
        praesentation: string
        print: string
        voreinstellung: boolean
      }
      beige: {
        bereich: string
        charakter: string
        website: string
        praesentation: string
        print: string
      }
      ivory: {
        bereich: string
        charakter: string
        website: string
        praesentation: string
        print: string
      }
      "warm-taupe": {
        bereich: string
        charakter: string
        website: string
        praesentation: string
        print: string
      }
      "pearl-white": {
        bereich: string
        charakter: string
        website: string
        praesentation: string
        print: string
      }
      mint: {
        bereich: string
        charakter: string
        website: string
        praesentation: string
        print: string
        vorlaeufig: boolean
      }
    }
    reserve: string[]
  }
}

export declare const typographyScale: {
  fluid: {
    viewport_min: number
    viewport_max: number
    base_min_px: number
    base_max_px: number
    ratio_min: number
    ratio_max: number
    fixed_steps: {
      "2xs": {
        min: number
        max: number
      }
      xs: {
        min: number
        max: number
      }
      sm: {
        min: number
        max: number
      }
    }
  }
  floor_px: number
  semantic_steps: {
    "2xs": number
    xs: number
    sm: number
    base: number
    lg: number
    xl: number
    "2xl": number
    "3xl": number
    "4xl": number
    "5xl": number
    "6xl": number
    "7xl": number
    "8xl": number
    "9xl": number
  }
  semantic_sizes_px: {
    "2xs": {
      min: number
      max: number
    }
    xs: {
      min: number
      max: number
    }
    sm: {
      min: number
      max: number
    }
    base: {
      min: number
      max: number
    }
    lg: {
      min: number
      max: number
    }
    xl: {
      min: number
      max: number
    }
    "2xl": {
      min: number
      max: number
    }
    "3xl": {
      min: number
      max: number
    }
    "4xl": {
      min: number
      max: number
    }
    "5xl": {
      min: number
      max: number
    }
    "6xl": {
      min: number
      max: number
    }
    "7xl": {
      min: number
      max: number
    }
    "8xl": {
      min: number
      max: number
    }
    "9xl": {
      min: number
      max: number
    }
  }
  line_height: {
    tight: number
    heading: number
    body: number
  }
  mappings: {
    heading: {
      xxs: string
      xs: string
      s: string
      m: string
      l: string
      xl: string
    }
    paragraph: {
      s: string
      m: string
      l: string
      xl: string
    }
    display: {
      s: {
        min_rem: number
        max_rem: number
      }
      m: {
        min_rem: number
        max_rem: number
      }
      l: {
        min_rem: number
        max_rem: number
      }
    }
  }
  roles: {
    display: {
      s: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      m: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      l: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      xl: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      "2xl": {
        font_size: string
        line_height: string
        letter_spacing: string
      }
    }
    heading: {
      xxs: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      xs: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      s: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      m: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      l: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      xl: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      "2xl": {
        font_size: string
        line_height: string
        letter_spacing: string
      }
    }
    paragraph: {
      xs: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      s: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      m: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      l: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
      xl: {
        font_size: string
        line_height: string
        letter_spacing: string
      }
    }
  }
  tracking: {
    tighter: string
    tight: string
    snug: string
    normal: string
    wide: string
    wider: string
    widest: string
    ultra: string
  }
}

export declare const systemPalettes: {
  neutral: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  info: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  success: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  warning: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
  danger: {
    label: string
    base: string
    shades: {
      "100": string
      "200": string
      "300": string
      "400": string
      "500": string
      "600": string
      "700": string
      "800": string
      "900": string
      "950": string
    }
  }
}

export declare const semanticTokenGroups: {
  id: string
  label: string
  icon: string
  tokens: {
    id: string
    label: string
    description?: string
  }[]
}[]

export declare const semanticDefaults: {
  "neo-light": {
    paper: string
    "background-base": string
    "background-secondary": string
    "background-tertiary": string
    "background-quaternary": string
    "background-quinary": string
    "background-hover": string
    "background-active": string
    "background-disabled": string
    "background-inverse": string
    "surface-elevated": string
    "background-skeleton": string
    "background-skeleton-element": string
    "background-overlay": string
    "background-transparency-low": string
    "background-transparency-mid": string
    "layer-01": string
    "layer-02": string
    "layer-03": string
    "text-primary": string
    "text-secondary": string
    "text-tertiary": string
    "text-disabled": string
    "text-inverse": string
    "text-difference": string
    "text-transparency-low": string
    "text-transparency-mid": string
    "text-link": string
    "text-link-hover": string
    "interactive-default": string
    "interactive-hover": string
    "interactive-active": string
    "interactive-visited": string
    "interactive-focus": string
    "text-on-interactive": string
    "background-accent": string
    "background-accent-secondary": string
    "on-accent": string
    "accent-underline": string
    "text-accent": string
    "border-primary": string
    "border-secondary": string
    "border-hairline": string
    "border-mid-dark": string
    "border-disabled": string
    "border-strong": string
    "border-inverse": string
    "border-control": string
    "feedback-success": string
    "feedback-warning": string
    "feedback-danger": string
    "feedback-info": string
    "text-success": string
    "text-warning": string
    "text-danger": string
    "text-info": string
    "border-success": string
    "border-warning": string
    "border-danger": string
    "border-info": string
    "background-success": string
    "background-warning": string
    "background-danger": string
    "background-info": string
    "on-success": string
    "on-warning": string
    "on-danger": string
    "on-info": string
    "on-surface": string
    "on-layer-01": string
    "on-layer-02": string
    "scrollbar-track": string
    "scrollbar-thumb": string
    "selection-bg": string
    "selection-color": string
    "paper-graphit": string
    "paper-beige": string
    "paper-ivory": string
    "paper-warm-taupe": string
    "paper-pearl-white": string
    "paper-mint": string
    "surface-stage": string
    "surface-card": string
    "surface-base": string
    "surface-01": string
    "surface-02": string
    "surface-03": string
    "surface-sunken": string
    "border-subtle": string
    "border-emphasis": string
    "accent-surface": string
    "accent-surface-hover": string
    "accent-surface-active": string
    "accent-on": string
    "accent-line": string
    "accent-text": string
    "focus-inner": string
    "focus-outer": string
  }
  "neo-dark": {
    paper: string
    "background-base": string
    "background-secondary": string
    "background-tertiary": string
    "background-quaternary": string
    "background-quinary": string
    "background-hover": string
    "background-active": string
    "background-disabled": string
    "background-inverse": string
    "surface-elevated": string
    "background-skeleton": string
    "background-skeleton-element": string
    "background-overlay": string
    "background-transparency-low": string
    "background-transparency-mid": string
    "layer-01": string
    "layer-02": string
    "layer-03": string
    "text-primary": string
    "text-secondary": string
    "text-tertiary": string
    "text-disabled": string
    "text-inverse": string
    "text-difference": string
    "text-transparency-low": string
    "text-transparency-mid": string
    "text-link": string
    "text-link-hover": string
    "interactive-default": string
    "interactive-hover": string
    "interactive-active": string
    "interactive-visited": string
    "interactive-focus": string
    "text-on-interactive": string
    "background-accent": string
    "background-accent-secondary": string
    "on-accent": string
    "accent-underline": string
    "text-accent": string
    "border-primary": string
    "border-secondary": string
    "border-hairline": string
    "border-mid-dark": string
    "border-disabled": string
    "border-strong": string
    "border-inverse": string
    "border-control": string
    "feedback-success": string
    "feedback-warning": string
    "feedback-danger": string
    "feedback-info": string
    "text-success": string
    "text-warning": string
    "text-danger": string
    "text-info": string
    "border-success": string
    "border-warning": string
    "border-danger": string
    "border-info": string
    "background-success": string
    "background-warning": string
    "background-danger": string
    "background-info": string
    "on-success": string
    "on-warning": string
    "on-danger": string
    "on-info": string
    "on-surface": string
    "on-layer-01": string
    "on-layer-02": string
    "scrollbar-track": string
    "scrollbar-thumb": string
    "selection-bg": string
    "selection-color": string
    "paper-graphit": string
    "paper-beige": string
    "paper-ivory": string
    "paper-warm-taupe": string
    "paper-pearl-white": string
    "paper-mint": string
    "surface-stage": string
    "surface-card": string
    "surface-base": string
    "surface-01": string
    "surface-02": string
    "surface-03": string
    "surface-sunken": string
    "border-subtle": string
    "border-emphasis": string
    "accent-surface": string
    "accent-surface-hover": string
    "accent-surface-active": string
    "accent-on": string
    "accent-line": string
    "accent-text": string
    "focus-inner": string
    "focus-outer": string
  }
  "customer-light": {
    paper: string
    "background-base": string
    "background-secondary": string
    "background-tertiary": string
    "background-quaternary": string
    "background-quinary": string
    "background-hover": string
    "background-active": string
    "background-disabled": string
    "background-inverse": string
    "surface-elevated": string
    "background-skeleton": string
    "background-skeleton-element": string
    "background-overlay": string
    "background-transparency-low": string
    "background-transparency-mid": string
    "layer-01": string
    "layer-02": string
    "layer-03": string
    "text-primary": string
    "text-secondary": string
    "text-tertiary": string
    "text-disabled": string
    "text-inverse": string
    "text-difference": string
    "text-transparency-low": string
    "text-transparency-mid": string
    "text-link": string
    "text-link-hover": string
    "interactive-default": string
    "interactive-hover": string
    "interactive-active": string
    "interactive-visited": string
    "interactive-focus": string
    "text-on-interactive": string
    "background-accent": string
    "background-accent-secondary": string
    "on-accent": string
    "accent-underline": string
    "text-accent": string
    "border-primary": string
    "border-secondary": string
    "border-hairline": string
    "border-mid-dark": string
    "border-disabled": string
    "border-strong": string
    "border-inverse": string
    "border-control": string
    "feedback-success": string
    "feedback-warning": string
    "feedback-danger": string
    "feedback-info": string
    "text-success": string
    "text-warning": string
    "text-danger": string
    "text-info": string
    "border-success": string
    "border-warning": string
    "border-danger": string
    "border-info": string
    "background-success": string
    "background-warning": string
    "background-danger": string
    "background-info": string
    "on-success": string
    "on-warning": string
    "on-danger": string
    "on-info": string
    "on-surface": string
    "on-layer-01": string
    "on-layer-02": string
    "scrollbar-track": string
    "scrollbar-thumb": string
    "selection-bg": string
    "selection-color": string
    "paper-graphit": string
    "paper-beige": string
    "paper-ivory": string
    "paper-warm-taupe": string
    "paper-pearl-white": string
    "paper-mint": string
  }
  "customer-dark": {
    paper: string
    "background-base": string
    "background-secondary": string
    "background-tertiary": string
    "background-quaternary": string
    "background-quinary": string
    "background-hover": string
    "background-active": string
    "background-disabled": string
    "background-inverse": string
    "surface-elevated": string
    "background-skeleton": string
    "background-skeleton-element": string
    "background-overlay": string
    "background-transparency-low": string
    "background-transparency-mid": string
    "layer-01": string
    "layer-02": string
    "layer-03": string
    "text-primary": string
    "text-secondary": string
    "text-tertiary": string
    "text-disabled": string
    "text-inverse": string
    "text-difference": string
    "text-transparency-low": string
    "text-transparency-mid": string
    "text-link": string
    "text-link-hover": string
    "interactive-default": string
    "interactive-hover": string
    "interactive-active": string
    "interactive-visited": string
    "interactive-focus": string
    "text-on-interactive": string
    "background-accent": string
    "background-accent-secondary": string
    "on-accent": string
    "accent-underline": string
    "text-accent": string
    "border-primary": string
    "border-secondary": string
    "border-hairline": string
    "border-mid-dark": string
    "border-disabled": string
    "border-strong": string
    "border-inverse": string
    "border-control": string
    "feedback-success": string
    "feedback-warning": string
    "feedback-danger": string
    "feedback-info": string
    "text-success": string
    "text-warning": string
    "text-danger": string
    "text-info": string
    "border-success": string
    "border-warning": string
    "border-danger": string
    "border-info": string
    "background-success": string
    "background-warning": string
    "background-danger": string
    "background-info": string
    "on-success": string
    "on-warning": string
    "on-danger": string
    "on-info": string
    "on-surface": string
    "on-layer-01": string
    "on-layer-02": string
    "scrollbar-track": string
    "scrollbar-thumb": string
    "selection-bg": string
    "selection-color": string
    "paper-graphit": string
    "paper-beige": string
    "paper-ivory": string
    "paper-warm-taupe": string
    "paper-pearl-white": string
    "paper-mint": string
  }
}

export declare const componentTokenGroups: {
  id: string
  label: string
  icon: string
  tokens: {
    id: string
    label: string
    type: string
    default?: string
    ref?: string
    darkDefault?: string
    group?: string
  }[]
  subGroups?: {
    id: string
    label: string
    tokenIds: string[]
  }[]
  subgroups?: {
    id: string
    label: string
    tokenIds: string[]
    tokens?: unknown[]
    category?: string
  }[]
  arenaConfig?: {
    type: string
    variants: {
      id: string
      label: string
      category: string
    }[]
    sizes: string[]
    tokenPattern: {
      background: string
      backgroundHover: string
      backgroundActive: string
      color: string
      borderColor: string
      height: string
      radius: string
      fontSize: string
      paddingX: string
      paddingY: string
    }
    states: string[]
    specimens: {
      id: string
      label: string
      renderType: string
    }[]
  }
}[]

export declare const foundationTokens: {
  radius: {
    label: string
    icon: string
    tokens: {
      null: {
        label: string
        value: string
        cssVar: string
      }
      xs: {
        label: string
        value: string
        cssVar: string
      }
      sm: {
        label: string
        value: string
        cssVar: string
      }
      md: {
        label: string
        value: string
        cssVar: string
      }
      lg: {
        label: string
        value: string
        cssVar: string
      }
      xl: {
        label: string
        value: string
        cssVar: string
      }
      "2xl": {
        label: string
        value: string
        cssVar: string
      }
      "3xl": {
        label: string
        value: string
        cssVar: string
      }
      "4xl": {
        label: string
        value: string
        cssVar: string
      }
      full: {
        label: string
        value: string
        cssVar: string
      }
    }
  }
  spacing: {
    label: string
    icon: string
    tokens: {
      "10": {
        label: string
        value: string
        cssVar: string
      }
      "11": {
        label: string
        value: string
        cssVar: string
      }
      "12": {
        label: string
        value: string
        cssVar: string
      }
      "13": {
        label: string
        value: string
        cssVar: string
      }
      "01": {
        label: string
        value: string
        cssVar: string
      }
      "02": {
        label: string
        value: string
        cssVar: string
      }
      "03": {
        label: string
        value: string
        cssVar: string
      }
      "04": {
        label: string
        value: string
        cssVar: string
      }
      "05": {
        label: string
        value: string
        cssVar: string
      }
      "06": {
        label: string
        value: string
        cssVar: string
      }
      "07": {
        label: string
        value: string
        cssVar: string
      }
      "08": {
        label: string
        value: string
        cssVar: string
      }
      "09": {
        label: string
        value: string
        cssVar: string
      }
    }
  }
  size: {
    label: string
    icon: string
    tokens: {
      xs: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      sm: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      md: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      lg: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      xl: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "2xl": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "touch-target": {
        label: string
        value: string
        type: string
        cssVar: string
      }
    }
  }
  shadow: {
    label: string
    icon: string
    tokens: {
      xs: {
        label: string
        value: string
        cssVar: string
      }
      sm: {
        label: string
        value: string
        cssVar: string
      }
      md: {
        label: string
        value: string
        cssVar: string
      }
      lg: {
        label: string
        value: string
        cssVar: string
      }
      xl: {
        label: string
        value: string
        cssVar: string
      }
    }
  }
  elevation: {
    label: string
    icon: string
    tokens: {
      base: {
        label: string
        value: string
        maps_to: string
        cssVar: string
        resolved_value: string
      }
      raised: {
        label: string
        value: string
        maps_to: string
        cssVar: string
        resolved_value: string
      }
      floating: {
        label: string
        value: string
        maps_to: string
        cssVar: string
        resolved_value: string
      }
      overlay: {
        label: string
        value: string
        maps_to: string
        cssVar: string
        resolved_value: string
      }
      modal: {
        label: string
        value: string
        maps_to: string
        cssVar: string
        resolved_value: string
      }
    }
  }
  opacity: {
    label: string
    icon: string
    tokens: {
      disabled: {
        label: string
        value: number
        cssVar: string
      }
      hover: {
        label: string
        value: number
        cssVar: string
      }
      focus: {
        label: string
        value: number
        cssVar: string
      }
      pressed: {
        label: string
        value: number
        cssVar: string
      }
      dragged: {
        label: string
        value: number
        cssVar: string
      }
      muted: {
        label: string
        value: number
        cssVar: string
      }
      medium: {
        label: string
        value: number
        cssVar: string
      }
      high: {
        label: string
        value: number
        cssVar: string
      }
      prominent: {
        label: string
        value: number
        cssVar: string
      }
      subtle: {
        label: string
        value: number
        cssVar: string
      }
    }
  }
  typography: {
    label: string
    icon: string
    tokens: {
      "font-body": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "font-heading": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "font-mono": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "weight-light": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-regular": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-medium": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-semibold": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-bold": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-black": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-heading": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-heading-strong": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-body": {
        label: string
        value: number
        type: string
        cssVar: string
      }
      "weight-mono": {
        label: string
        value: number
        type: string
        cssVar: string
      }
    }
  }
  tracking: {
    label: string
    icon: string
    tokens: {
      tighter: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      tight: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      snug: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      normal: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      wide: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      wider: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      widest: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      ultra: {
        label: string
        value: string
        type: string
        cssVar: string
      }
    }
  }
  motion: {
    label: string
    icon: string
    tokens: {
      "easing-informative": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "easing-focused": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "easing-expressive": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "duration-quick": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "duration-base": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "duration-slow": {
        label: string
        value: string
        type: string
        cssVar: string
      }
    }
  }
  border: {
    label: string
    icon: string
    tokens: {
      "width-null": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "width-xs": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "width-sm": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "width-md": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "width-lg": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "width-xl": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "style-solid": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "style-dashed": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "style-dotted": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "style-double": {
        label: string
        value: string
        type: string
        cssVar: string
      }
      "style-none": {
        label: string
        value: string
        type: string
        cssVar: string
      }
    }
  }
  zindex: {
    label: string
    icon: string
    tokens: {
      base: {
        label: string
        value: number
        cssVar: string
      }
      dropdown: {
        label: string
        value: number
        cssVar: string
      }
      sticky: {
        label: string
        value: number
        cssVar: string
      }
      fixed: {
        label: string
        value: number
        cssVar: string
      }
      header: {
        label: string
        value: number
        cssVar: string
      }
      sidebar: {
        label: string
        value: number
        cssVar: string
      }
      drawer: {
        label: string
        value: number
        cssVar: string
      }
      "modal-backdrop": {
        label: string
        value: number
        cssVar: string
      }
      modal: {
        label: string
        value: number
        cssVar: string
      }
      notification: {
        label: string
        value: number
        cssVar: string
      }
      toast: {
        label: string
        value: number
        cssVar: string
      }
      tooltip: {
        label: string
        value: number
        cssVar: string
      }
      "skip-link": {
        label: string
        value: number
        cssVar: string
      }
    }
  }
  focus: {
    label: string
    icon: string
    tokens: {
      color: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      width: {
        label: string
        value: string
        type: string
        cssVar: string
      }
      offset: {
        label: string
        value: string
        type: string
        css_property: string
        description: string
        cssVar: string
      }
      inset: {
        label: string
        value: string
        type: string
        css_property: string
        description: string
        cssVar: string
      }
      style: {
        label: string
        value: string
        cssVar: string
      }
    }
  }
  media: {
    label: string
    icon: string
    tokens: {
      auto: {
        label: string
        value: string
        cssVar: string
      }
      "1-1": {
        label: string
        value: string
        cssVar: string
      }
      "3-2": {
        label: string
        value: string
        cssVar: string
      }
      "2-3": {
        label: string
        value: string
        cssVar: string
      }
      "4-3": {
        label: string
        value: string
        cssVar: string
      }
      "3-4": {
        label: string
        value: string
        cssVar: string
      }
      "16-9": {
        label: string
        value: string
        cssVar: string
      }
      "9-16": {
        label: string
        value: string
        cssVar: string
      }
      "2-1": {
        label: string
        value: string
        cssVar: string
      }
      "1-2": {
        label: string
        value: string
        cssVar: string
      }
    }
  }
  elements: {
    label: string
    icon: string
    groups: {
      label: string
      items: {
        property: string
        value: string
      }[]
    }[]
  }
  themes: {
    label: string
    icon: string
    themeList: {
      id: string
      label: string
      role: string
      colorScheme: string
      mixTarget: string
      desc: string
    }[]
  }
}

export declare const navigationTree: {
  id: string
  label: string
  icon: string
  children: {
    id: string
    label: string
    icon?: string
    section?: string
    isSubgroup?: boolean
    children?: {
      id: string
      label: string
      icon: string
      section: string
    }[]
  }[]
}[]
